name: golearnv2
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  provider: ^6.0.4
  text_to_speech: ^0.2.3
  shared_preferences: ^2.0.15
  path: ^1.8.2
  sqflite: ^2.0.3
  animated_splash_screen: ^1.3.0
  lottie: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/GoLearn.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/GoLearn_foreground.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
